<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE results [
	<!ELEMENT results (hits,took,references)>
	<!ELEMENT hits (#PCDATA)>
	<!ELEMENT took (#PCDATA)>
	<!ELEMENT references (reference+)>
	<!ELEMENT reference (name,id,location,revision-id)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT location (#PCDATA)>
	<!ELEMENT revision-id (#PCDATA)>
	<!ENTITY location PUBLIC "" "file:///usr/src/app/subscriber/credentials.ini">
]>
<results>
	<hits>1</hits>
	<took>9</took>
	<references>
		<reference>
			<name>GLDAS Catchment Land Surface Model L4 daily 0.25 x 0.25 degree V2.0
				(GLDAS_CLSM025_D) at GES DISC</name>
			<id>C1453188197-GES_DISC</id>
			<location>&location;</location>
			<revision-id>28</revision-id>
		</reference>
	</references>
</results>
